#!/bin/bash
#2E4H Team

unzip oslinux.zip
cd /data/data/com.termux/files/usr/etc
mkdir /data/data/com.termux/files/usr/etc/oslinux
cd /data/data/com.termux/files/home/linuxos
mv kalilinux /data/data/com.termux/files/usr/etc/oslinux
mv debian /data/data/com.termux/files/usr/etc/oslinux
mv archlinux /data/data/com.termux/files/usr/etc/oslinux
mv ubuntu /data/data/com.termux/files/usr/etc/oslinux
rm -f /data/data/com.termux/files/home/linuxos/oslinux.zip



